In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv("houses_flats_final.csv")

In [4]:
df.head()

,bedrooms,baths,price,area_sqft,kitchens,store_rooms,gym,furnishing_score,agePossession,property_type,has_servant_room,luxury_category,floor_category
0,4.0,4.0,4.55,3264.0,1.0,1.0,0,37,New Property,flat,1,Very High,Mid Floor
1,4.0,5.0,4.50,3318.4,1.0,0.0,0,31,New Property,flat,1,Very High,Mid Floor
2,3.0,4.0,3.55,2720.0,1.0,1.0,1,49,New Property,flat,1,Very High,Mid Floor
3,4.0,4.0,4.45,2067.2,2.0,1.0,0,18,New Property,flat,1,Very High,Mid Floor
4,4.0,5.0,4.65,3318.4,1.0,1.0,0,18,New Property,flat,1,Very High,Mid Floor

In [5]:
df.shape

(23081, 13)

In [6]:
df['furnishing_score'].value_counts()

furnishing_score
25    9272
15    3470
0     1738
49    1445
24     983
14     653
39     518
5      488
7      462
6      406
8      402
12     370
3      341
13     301
11     298
10     172
23     148
2      146
18     144
16     144
22     142
9      134
1      130
20     109
4       97
47      88
17      74
37      68
21      55
33      42
19      37
30      34
31      31
28      28
40      19
34      19
32      16
43      13
41      12
26      11
38       8
42       6
27       5
35       1
29       1
Name: count, dtype: int64

In [7]:
df['furnishing_type'] = pd.cut(
    df['furnishing_score'],
    bins=[-1, 0, 10, 25, 100],
    labels=[
        'Unfurnished',
        'Semi-Furnished',
        'Furnished',
        'Luxury Furnished'
    ]
)

In [9]:
df=df.drop(columns='furnishing_score')

In [10]:
df.head()

,bedrooms,baths,price,area_sqft,kitchens,store_rooms,gym,agePossession,property_type,has_servant_room,luxury_category,floor_category,furnishing_type
0,4.0,4.0,4.55,3264.0,1.0,1.0,0,New Property,flat,1,Very High,Mid Floor,Luxury Furnished
1,4.0,5.0,4.50,3318.4,1.0,0.0,0,New Property,flat,1,Very High,Mid Floor,Luxury Furnished
2,3.0,4.0,3.55,2720.0,1.0,1.0,1,New Property,flat,1,Very High,Mid Floor,Luxury Furnished
3,4.0,4.0,4.45,2067.2,2.0,1.0,0,New Property,flat,1,Very High,Mid Floor,Furnished
4,4.0,5.0,4.65,3318.4,1.0,1.0,0,New Property,flat,1,Very High,Mid Floor,Furnished

In [11]:
# Split features and target
X = df.drop(columns=['price'])
y = df['price']

In [12]:
# Apply log1p transformation
y_transformed = np.log1p(y)